### ISSUE TITLE
Umbrella issue to improve and fix our docs pipelines

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/learn#1360]
After our sync with @Ancairon and taking into consideration current open issues we need to change the following

1. GH link convert
      - Bug_1: Our current approach does not take into consideration links that span between two lines
      - Improvement_1: Our current approach converts only markdown reference links `format: [. . .](. . .)`
      
2. Provide pages for the dropdown sidebar items
      - Bug_1: We investigate why a document may or may not appear as a page in a dropdown category's sidebar. This is a side effect based on this https://docusaurus.io/docs/sidebar/items#generated-index-page feature.  To that end; when we want to make a folder (drop-down category) with an index page attached to it, we create a page inside this folder with the same name (same as the category folder). **Note** the final name in learn needs to be the same as the folder. **Sideeffect** our process to convert GH docs to actual learn links must identify cases like this

3. Ingest repos: We don't contain useful ingested repos

4. Qos for documents for all of our repos
      - Bug_1: It appears that our ingest  script does not identify correctly documents that contain no metadata.

5.  Detach sidebar_label metadata from the folder's output path, at the moment when you change the sidebar_label the output file is changing and eventually the learn final path, this will introduce broken links when we reference learn outside of it.

Summary
 - [x] #1468
 - [x]  Find any `http(s)://` link and try to convert it through our map to learn the final path (document page) @Ancairon fixes: https://github.com/netdata/learn/issues/1346 
 - [x]  GH docs links converter must identify links that have a tail with a folder with the same context and omit the last one, e.g `References/collectors/collectors` will be  `References/collectors/` @Ancairon
 - [x]  Update the guidelines on how we make documents for these cases (Pages for drop-down categories) @AncaironOnly people editing the map.tsv will be able to handle pages like this.
 - [x]  Include repos `netdata/helmchart` and  `netdata/agent-service-discovery` @Ancairon fixes: https://github.com/netdata/learn/issues/1301
 - [x]  Browse on these repos and include any document you may want (add metadata) (`netdata/helmchart` and  `netdata/agent-service-discovery`) 
 - [ ]  ~~`readMetdataFromDocs`: Needs to Identify correctly that it reads valid and actual metadata. @tkatsoulas~~ 
 - [ ] ~~Add a new metadata `learn_output_file` (after our current `sidebar_label`) and amend the ingest process to move them based on this. @tkatsoulas~~ 
 - [ ] ~~Update our documentation instructions:
        1.  When someone changes a file position, they need to update the `custom_edit_url` of this file, and then `git grep` in any of our repo with the old file path and change it to the new one (we can automate this in time, to be done without dev to take care of it) @Ancairon~~
        2. ~~When someone touches the `learn_rel_path` and the newly added `learn_output_file` they need to add a redirect link in the learn site, (we can automate this in time) @Ancairon Doesn't work this way anymore.~~
        3. ~~Remove folder redirect from learn redirect policies @tkatsoulas~~
        4. ~~Periodic check for chain redirects which may create loops. (automate in time) @tkatsoulas~~
        ~~These pipelines guarantee no broken links in learn both from outside world or inside.~~ fixes: https://github.com/netdata/learn/issues/1352
