### ISSUE TITLE
GoLive checklist

### ISSUE THREAD

**Issue by cakrit** [netdata/learn#1407]
- [x] Resolve security vulnerabilities https://github.com/netdata/learn/security/dependabot @Ancairon 
- [x] Prepare redirects -  #1402 @Ancairon or @tkatsoulas 
- [x] Fix capitalization of collectors directories @Ancairon #1412 
- [x] Finish reorg - @cakrit
- [x] Add missing headings - @cakrit @Ancairon 
- [x] Modify ingest to make nightly the only available version @Ancairon #1424 

Other?
