### ISSUE TITLE
Integration Pages in Learn

### ISSUE THREAD

**Issue by Ancairon** [netdata/learn#1767]
This is a child issue of https://github.com/netdata/product/issues/3169.

In short, we need to be able to use `integrations.js` as the single source of truth for integrations.
I will keep on updating the issue with task lists in this initial planning phase.

```[tasklist]
### Release Tasklist Steps
- [ ] https://github.com/netdata/learn/issues/1784
- [x] Merge https://github.com/netdata/netdata/pull/15995
- [x] Turn off ingest temporarily
- [x] Merge the big PRs that generate the markdown files https://github.com/netdata/go.d.plugin/pull/1349 and https://github.com/netdata/netdata/pull/16062
- [x] Make a PR addressing the manual markdown changes needed on netdata/netdata. This means making manual symlinks where needed https://github.com/netdata/netdata/pull/16062
- [x] Make a PR addressing the manual markdown changes needed on netdata/go.d.plugin (same actions needed as above task)) https://github.com/netdata/go.d.plugin/pull/1349
- [x] Merge the ingest PR on Learn https://github.com/netdata/learn/pull/1800
```

```[tasklist]
### Prerequisites
- [x] ~~*[This can be done separately from developing the script, just prior to merging]* Inspect READMEs that have more info than integrations.js provides and possibly make them new files so we can edit them afterwards.~~ **Moved to Release Tasklist Steps**
- [x] ~~Decide what will happen with multi module plugins, ideally they would have readmes that will be in a `docs` folder inside that plugin, with the master readme explaining how it works, or giving a Birdseye view~~ **Solution:** All collectors will have an `integrations` folder, to be able to present multi module integrations. Then, in each such folder that only one file is found, a README symlink will be created on the parent folder.
- [x] ~~Decide if we want all categories in Learn, meaning `Deploy`, `Exporters`, `Notifications` etc.~~ **Answer:** Only deploy will be excluded, all the other integrations will have their own markdown files.
- [x] Noting that Kubernetes and systemd categories must be renamed (or their children) to not have Kubernetes (category) -> Kubernetes (integration) as this moves them up in the alphabetical order in Learn.
```

```[tasklist]
### New script requirements
- [x] There needs to be an action in the netdata repo and one in the go.d, running the script with the integrations.js file to generate the markdown files. https://github.com/netdata/go.d.plugin/pull/1330 https://github.com/netdata/netdata/pull/15893
- [x] It needs to take care to convert UI tags to markdown ones.
- [x] It needs to read `integrations.js` and produce from it markdown files.
- [x] To prevent confusion and mess, integrations other than collectors will have their README markdown replaced, but collector integrations will be in a `integrations` directory in each collector. If then it is found that the directory contains only one integration, it means that a symlink can be made to the parent README.md, and it will be made. Otherwise, the outer README.md should state some info about the plugin. The ingest then will take into account only markdown files and not symlinks.
- [x] The generated files should have all the metadata Learn needs to categorize them as Docusaurus metadata, plus a note to not edit directly.
```

```[tasklist]
### Updates to Learn scripts
- [x] Learn should then ingest these markdowns and append to the map the entries before the ingest process.
- [x] The map might need some placeholder to indicate where each category will fall into.
- [x] Ordering will probably be limited by the current implementation to only alphabetical categories
- [x] ~~sidebar position needs to be handled, probably by an indicator in the map, that gives a range of row numbers to the integrations~~ **Solution**: The entries are inserted before the ingest process actually begins, so this is handled
- [x] Take care of multi integration collector READMEs
- [x] check sorting for category items inside data collection
- [x] Make a PR that changes the map (which is a Google Sheet with functions) to the required format so the new ingest can know where to place all the integrations **Moved to Release Tasklist Steps**
```

As this project starts, more items might be added to the list as issues/requirements come up.

```[tasklist]
### Tasks
- [x] Make a PR addressing the action needed in netdata/netdata https://github.com/netdata/netdata/pull/15893
- [x] Make a PR that introduces a script that autogenerates collectors/COLLECTORS.md https://github.com/netdata/netdata/pull/15995
- [x] Make a PR addressing the action needed in netdata/go.d.plugin https://github.com/netdata/go.d.plugin/pull/1330
```

**Comment by Ancairon** [comment]
Current form can be seen: https://staging--netdata-docusaurus.netlify.app/docs/architecture

Next task is to check the broken links, which would be dealing with READMEs that are now out of place. Specifically the ones that come from collectors that generate more than one integrations.

Noting that Kubernetes and systemd categories must be renamed (or their children) to not have Kubernetes (category) -> Kubernetes (integration) as this moves them up in the alphabetical order in Learn.
