### ISSUE TITLE
Preserve README info of collectors

### ISSUE THREAD

**Issue by Ancairon** [netdata/learn#1784]
## Description

due to the lack of issue template options on netdata/netdata, let's track this here.

as tasks come up they will be added here.

```[tasklist]
### Tasks
- [ ] xenstat: @thiagoftsm debbugging section missing https://github.com/netdata/netdata/pull/15950
- [ ] slabinfo: @thiagoftsm add the note about official native packages, probably in the prerequisites section as an item https://github.com/netdata/netdata/pull/15951
- [x] tor: @MrZammler add the missing requirements to the prerequisites from the README https://github.com/netdata/netdata/pull/15945
- [ ] tomcat: @Ancairon fix a typo in the prerequisites
- [ ] sensors: @andrewm4894 add the line about not working on your device (and needing to use the other sensors collector) as a troubleshooting step
- [ ] samba: @Ancairon should say that the plugin is disabled by default and how to enable it, probably in prerequisites section
- [ ] nsd: @Ancairon add nsd version prerequisite
- [ ] megacli: @tkatsoulas fix commands not in backticks and should say that the plugin is disabled by default and how to enable it, probably in prerequisites section
- [x] hpssa: @MrZammler should say that the plugin is disabled by default and how to enable it, probably in prerequisites section https://github.com/netdata/netdata/pull/15945
- [ ] hddtemp: @Ancairon check details in configuration options
- [x] go_expvar: @MrZammler should say that the plugin is disabled by default and how to enable it, probably in prerequisites section https://github.com/netdata/netdata/pull/15945
- [ ] fail2ban: @andrewm4894 populate the metadata with README info
- [ ] changefinder: @andrewm4894 populate the metadata with README info (original author of the collector I feel)
- [ ] adaptec_raid: @tkatsoulas make some code text into code blocks, state that the plugin is disabled by default and how to enable it (probably put it in prerequisites)
- [ ] perf: @Ancairon prerequisites section about official rpm packages, fact that it is disabled by default, command keywords, debugging
- [ ] nfaact: @thiagoftsm add debugging section and prerequisites
- [ ] freeipmi: @thiagoftsm prerequisites need to be fixed https://github.com/netdata/netdata/pull/15952 @Ancairon to follow up, as some stuff is missing from the README still
```

**Comment by Ancairon** [comment]
This is done
